name: duit_kernel
description: "Core library for flutter_duit package.  Contains reusable models for developing third-party packages."
version: 4.0.1
repository: https://github.com/lesleysin/duit_kernel
funding:
  - https://boosty.to/duit_foundation

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  ansicolor: ^2.0.3
  flutter:
    sdk: flutter
  meta: ^1.15.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
